#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-deployment
#  labels:
#    app: nginx
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: nginx
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag}}"
#        ports:
#        - containerPort: 80
#          name: nginx-port
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  labels:
#    app.kubernetes.io/name: proxy
#spec:
#  containers:
#  - name: nginx
#    image: nginx:stable
#    ports:
#      - containerPort: 80
#        name: http-web-svc
#---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: http-web-svc
  type: LoadBalancer
#---
#apiVersion: v1
#kind: EndpointSlice
#metadata:
#  name: nginx-service-1 # by convention, use the name of the Service
#                     # as a prefix for the name of the EndpointSlice
#  labels:
#    # You should set the "kubernetes.io/service-name" label.
#    # Set its value to match the name of the Service
#    kubernetes.io/service-name: nginx-service
#addressType: IPv4
#ports:
#  - name: ''
#    appProtocol: http
#    protocol: TCP
#    port: 80
